# Generated by Django 3.2 on 2023-02-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='usertype',
            field=models.CharField(default='Telesale', max_length=100),
        ),
    ]
