# Generated by Django 3.1 on 2023-02-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleapp', '0003_auto_20230223_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telesale_team', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('commu_team1', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('online_team', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('mynmar_team', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('duckbet', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('mughauy', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('slak_thai', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('phone_number', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('quality', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('interest', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('inwork', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('absent', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('employee', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
            ],
        ),
    ]
