# Generated by Django 3.1 on 2023-03-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleapp', '0004_expenses_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='created',
        ),
    ]
