# Generated by Django 3.1 on 2023-02-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleapp', '0004_teamstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstat',
            name='stamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
