# Generated by Django 3.1 on 2023-03-08 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teleapp', '0005_remove_expenses_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duckbet', models.IntegerField(default=0)),
                ('mughauy', models.IntegerField(default=0)),
                ('thailotto', models.IntegerField(default=0)),
                ('create', models.DateTimeField(auto_now_add=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teleapp.team')),
            ],
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
