# Generated by Django 3.1 on 2023-02-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleapp', '0005_teamstat_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstat',
            name='commu_team2',
            field=models.IntegerField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
