# Generated by Django 3.2.4 on 2023-03-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleapp', '0007_auto_20230308_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
